spring:
  config:
    import: "classpath:/application-dev-secret.yml"
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update

  # Thymeleaf 설정(email)
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    cache: false

logging:
  level:
    org:
      springframework:
        security: TRACE

origins: http://localhost:3000